services:
  - type: web
    name: crypto-bot
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: TELEGRAM_TOKEN
        value: "8063113740:AAGC-9PHzZD65jPad2lxP5mTmlWuQwvKwrU"
